"""Pydantic v2 schemas for the structured-comparison call (Phase 1.7).

These are the public, Pydantic-validated wire shapes for the LLM call
in :mod:`src.llm.compare`. The fields are exactly what
``docs/PHASE-1.md`` §1.7 specifies — ``CompetitorVerdict``,
``MarketScope``, and ``IdeaVerdict`` — and the JSON Schema instructor
generates from them is the source of truth for the structured output
contract with Claude.

Why Pydantic v2 (and not dataclasses / TypedDict)
-------------------------------------------------
- ``instructor`` wraps Pydantic models natively — it inspects the
  model's JSON schema and feeds it to the LLM as a tool input
  contract, then validates the response against the model. Dataclasses
  and TypedDicts don't get the same first-class treatment.
- Pydantic v2 emits clean JSON Schema (no ``title``/``default``
  noise), so the LLM sees a compact, unambiguous contract.
- The schemas are reused on the API boundary (1.8) — FastAPI uses
  the same models for request/response validation, so a single
  class is the source of truth for "what does an IdeaVerdict look
  like" in both the LLM call and the HTTP layer.

Stability
---------
The field names and types here are part of the public contract.
Renaming a field is a breaking change to the LLM call, the API
response, and the test fixture ``tests/fixtures/compare_smoke.json``.
If you need to deprecate a field, add a new one and keep the old
one populated for one release.
"""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


# ---------------------------------------------------------------------------
# Market-scope enum
# ---------------------------------------------------------------------------


class MarketScope(str, Enum):
    """Four-state directional signal for the competitive landscape.

    This is a *stub* (per SPEC.md and the AGENTS.md pitfalls list).
    It is generated by the LLM from the top-K density and the
    structured comparison, **not** by a real SEMrush/Ahrefs pipeline.
    The README labels it as a directional signal; "future work:
    integrate SEMrush / SimilarWeb when budget allows."

    The string values are part of the public API contract — the
    frontend in Phase 1.9 keys its colour coding off them.
    """

    WIDE_OPEN = "wide_open"
    CROWDED_BUT_GROWING = "crowded_but_growing"
    SATURATED = "saturated"
    NICHE_BUT_REAL = "niche_but_real"


# ---------------------------------------------------------------------------
# Per-competitor structured verdict
# ---------------------------------------------------------------------------


class CompetitorVerdict(BaseModel):
    """Structured comparison of the idea vs. one similar company.

    All five list fields are *strings*, not nested objects. The LLM
    is asked to write 2–4 short, declarative phrases per field — the
    frontend renders them as chips, bullets, and tags. The contract
    is "short, evidence-anchored, no marketing fluff", which is
    easier to enforce in the system prompt than to validate
    structurally.

    ``confidence`` is the model's self-reported 0–1 confidence. It
    is *not* the cosine similarity from /search — the LLM sees both
    the cosine scores and the company descriptions, and returns a
    holistic "how much of a real competitor is this" signal. The
    eval harness in Phase 1.6 will measure how well it calibrates.
    """

    # ``extra='forbid'`` means a misbehaving LLM that emits an
    # unexpected field raises a validation error instead of being
    # silently coerced. We want loud failures, not quiet drift.
    model_config = ConfigDict(extra="forbid")

    company_id: int = Field(
        ...,
        description="Numeric id of the company in the local `companies` table.",
    )
    name: str = Field(..., description="Human-readable company name.")
    similarity_axes: list[str] = Field(
        default_factory=list,
        description=(
            "Short phrases naming the dimensions on which this company "
            "is similar to the idea (e.g. 'AI-assisted drafting', 'SMB "
            "market', 'subscription pricing'). 2–4 phrases."
        ),
    )
    key_differences: list[str] = Field(
        default_factory=list,
        description=(
            "Short phrases naming the dimensions on which this company "
            "differs from the idea (e.g. 'enterprise-only', 'no AI "
            "drafting', 'larger entity-extraction model'). 1–3 phrases."
        ),
    )
    likely_failure_modes: list[str] = Field(
        default_factory=list,
        description=(
            "Why this competitor might lose to the user's idea, or "
            "might be a hard incumbent. 1–3 phrases. Honest — 'they "
            "have strong distribution' is a valid answer."
        ),
    )
    evidence_links: list[str] = Field(
        default_factory=list,
        description=(
            "URLs the model used as evidence (company url, blog "
            "post, founder interview, etc.). Empty list if the model "
            "relied on the supplied description alone."
        ),
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description=(
            "Model self-reported 0–1 confidence that this company is a "
            "real competitor to the idea. Not the cosine similarity — "
            "the LLM's holistic judgment after reading both."
        ),
    )


# ---------------------------------------------------------------------------
# Top-level IdeaVerdict
# ---------------------------------------------------------------------------


#: Hard cap on the number of competitors in a verdict. PHASE-1.md §1.7
#: says "hard cap at top-3 (configurable)"; this constant is the
#: default. The /ideas/analyze endpoint (1.8) can override it via
#: env or a query param.
DEFAULT_TOP_K = 3
MAX_TOP_K = 5  # the prompt template enforces up to 5; we still cap to 3 by default


class IdeaVerdict(BaseModel):
    """The full structured response to ``POST /ideas/analyze``.

    This is the wire shape returned to the frontend and the unit of
    work for the eval harness in Phase 1.6.

    ``top_competitors`` is the *structured* result. The cosine
    similarities from /search are not preserved here — Phase 1.6's
    eval harness can re-derive them from the IDs if needed.

    ``supporting_evidence`` is the model's *general* evidence (blog
    posts, market reports) for the market-scope claim, distinct
    from the per-competitor ``evidence_links`` lists.
    """

    model_config = ConfigDict(extra="forbid")

    idea: str = Field(
        ...,
        description="The original user-supplied idea text, echoed back.",
    )
    top_competitors: list[CompetitorVerdict] = Field(
        default_factory=list,
        description=(
            "Ranked list of similar past launches. Length is the "
            "configured top-K, default 3. Same order as /search "
            "returned."
        ),
    )
    market_scope: MarketScope = Field(
        ...,
        description=(
            "Four-state directional signal: wide_open, "
            "crowded_but_growing, saturated, niche_but_real. Stub — "
            "see the docstring in `MarketScope`."
        ),
    )
    market_scope_rationale: str = Field(
        ...,
        description=(
            "1–2 sentence explanation of why the model picked the "
            "market_scope value. Anchors the stub in evidence so "
            "users can tell when the model is hand-waving."
        ),
    )
    supporting_evidence: list[str] = Field(
        default_factory=list,
        description=(
            "URLs that support the market_scope verdict as a whole "
            "(market reports, HN threads, blog posts). Distinct "
            "from per-competitor `evidence_links`."
        ),
    )
