"""Tests for the Phase 4.1 MarketScopeQuant envelope (card t_008aef26).

Scope:
- ``MarketScopeQuant`` validates the six fields with the type-level
  guardrails (competitor_count/recent_3y_count >=0, saturation_index
  in [0,1], growth_rate >=0) — the spec's "no breaking changes to
  the IdeaVerdict schema" rule.
- ``MarketScopeEvidence`` validates source ∈ {"corpus", "web"}, and
  the cross-source field rules (company_id for corpus, url for web).
- ``MarketScopeSignal`` composes the three layers with confidence
  tied to quantitative population.
- ``IdeaVerdict`` accepts the new optional ``market_scope_signal``
  field with ``default=None`` — the Phase 1.7/1.8/1.11 fixtures
  that DON'T set the field still parse.
- The 4-direction ``MarketScope`` enum strings are unchanged
  (``wide_open / crowded_but_growing / saturated / niche_but_real``)
  so the frontend ``marketScope.ts`` colour-coded chip keeps
  working — verified by ``model_dump(mode="json")``.
- ``model_dump(mode="json")`` produces JSON-safe shapes (datetime →
  ISO-8601 string, dict preserved, optional fields nullable).
- ``OpenAPI`` schema for the new envelope is generated by Pydantic v2
  and references the same field names the TypeScript frontend
  mirrors in ``src/frontend/src/lib/api.ts`` — checked via
  ``model_json_schema()``.

What this does NOT cover:
- The deterministic direction rules (4.2). They're a separate card.
- SearXNG/Firecrawl web augmentation (4.3).
- LLM synthesis over the new envelope (4.4).
- Eval-harness metric (4.5).
- Frontend badge wiring (4.6).
- Helena review (4.7).

Hard rule from the card body:
> No breaking changes to the IdeaVerdict schema. The new fields are
> additive with sensible defaults. The 4-direction enum values
> (wide_open / crowded_but_growing / saturated / niche_but_real)
> are part of the public API contract.

These tests are pure — they don't touch the DB, the API, or any
external service.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone

import pytest
from pydantic import ValidationError

from src.llm.schemas import (
    CompetitorVerdict,
    IdeaVerdict,
    MarketScope,
    MarketScopeConfidence,
    MarketScopeEvidence,
    MarketScopeQuant,
    MarketScopeSignal,
)


# ---------------------------------------------------------------------------
# MarketScopeQuant — type-level guardrails
# ---------------------------------------------------------------------------


class TestMarketScopeQuant:
    """The six-field quantitative layer carries its own type-level guardrails."""

    def test_minimal_valid_quant(self) -> None:
        """The spec requires competitor_count, recent_3y_count, saturation_index;
        search_volume_proxy and growth_rate default to None. category_distribution
        defaults to {} so a zero-neighborhood doesn't break the validator."""
        q = MarketScopeQuant(
            competitor_count=0,
            recent_3y_count=0,
            saturation_index=0.0,
        )
        assert q.competitor_count == 0
        assert q.recent_3y_count == 0
        assert q.category_distribution == {}
        assert q.search_volume_proxy is None
        assert q.saturation_index == 0.0
        assert q.growth_rate is None

    def test_full_quant_round_trips(self) -> None:
        """All six fields populated — exercises the full envelope."""
        q = MarketScopeQuant(
            competitor_count=200,
            recent_3y_count=80,
            category_distribution={"B2B SaaS": 60, "AI": 40, "fintech": 30, "other": 70},
            search_volume_proxy=42,
            saturation_index=1.0,
            growth_rate=0.4,
        )
        dumped = q.model_dump(mode="json")
        assert dumped == {
            "competitor_count": 200,
            "recent_3y_count": 80,
            "category_distribution": {
                "B2B SaaS": 60,
                "AI": 40,
                "fintech": 30,
                "other": 70,
            },
            "search_volume_proxy": 42,
            "saturation_index": 1.0,
            "growth_rate": 0.4,
        }

    def test_negative_competitor_count_rejected(self) -> None:
        """competitor_count has ge=0 — negative values are invalid."""
        with pytest.raises(ValidationError) as exc:
            MarketScopeQuant(
                competitor_count=-1,
                recent_3y_count=0,
                saturation_index=0.0,
            )
        assert "competitor_count" in str(exc.value)

    def test_negative_recent_3y_count_rejected(self) -> None:
        with pytest.raises(ValidationError) as exc:
            MarketScopeQuant(
                competitor_count=10,
                recent_3y_count=-1,
                saturation_index=0.05,
            )
        assert "recent_3y_count" in str(exc.value)

    def test_saturation_index_must_be_in_unit_interval(self) -> None:
        """saturation_index has ge=0, le=1 — outside [0, 1] is invalid."""
        with pytest.raises(ValidationError) as exc:
            MarketScopeQuant(
                competitor_count=10,
                recent_3y_count=2,
                saturation_index=1.5,
            )
        assert "saturation_index" in str(exc.value)

        with pytest.raises(ValidationError):
            MarketScopeQuant(
                competitor_count=10,
                recent_3y_count=2,
                saturation_index=-0.1,
            )

    def test_negative_growth_rate_rejected(self) -> None:
        """growth_rate has ge=0 — negative is invalid when explicitly set."""
        with pytest.raises(ValidationError) as exc:
            MarketScopeQuant(
                competitor_count=10,
                recent_3y_count=2,
                saturation_index=0.05,
                growth_rate=-0.1,
            )
        assert "growth_rate" in str(exc.value)

    def test_negative_search_volume_proxy_rejected(self) -> None:
        """search_volume_proxy has ge=0 when set — negative is invalid."""
        with pytest.raises(ValidationError) as exc:
            MarketScopeQuant(
                competitor_count=10,
                recent_3y_count=2,
                saturation_index=0.05,
                search_volume_proxy=-5,
            )
        assert "search_volume_proxy" in str(exc.value)

    def test_extra_fields_forbidden(self) -> None:
        """MarketScopeQuant has extra='forbid' — a misbehaving caller adding
        an unexpected field must fail loudly rather than be silently dropped."""
        with pytest.raises(ValidationError) as exc:
            MarketScopeQuant(  # type: ignore[call-arg]
                competitor_count=10,
                recent_3y_count=2,
                saturation_index=0.05,
                some_unknown_field="oops",
            )
        assert "some_unknown_field" in str(exc.value)


# ---------------------------------------------------------------------------
# MarketScopeEvidence — cross-source field rules
# ---------------------------------------------------------------------------


class TestMarketScopeEvidence:
    """Each evidence entry has source ∈ {corpus, web}, with source-specific
    fields. The Pydantic validator doesn't cross-check (company_id required
    for corpus, url required for web) because that's the 4.4 LLM synthesis's
    job — but we verify the field set is open."""

    def _now(self) -> datetime:
        return datetime(2026, 7, 2, 9, 0, 0, tzinfo=timezone.utc)

    def test_corpus_evidence(self) -> None:
        e = MarketScopeEvidence(
            source="corpus",
            company_id=42,
            as_of=self._now(),
        )
        dumped = e.model_dump(mode="json")
        assert dumped["source"] == "corpus"
        assert dumped["company_id"] == 42
        assert dumped["url"] is None
        assert dumped["snippet"] is None
        # Pydantic v2 emits UTC datetimes with the 'Z' suffix on JSON
        # serialisation (rather than the '+00:00' offset form).
        assert dumped["as_of"] == "2026-07-02T09:00:00Z"

    def test_web_evidence(self) -> None:
        e = MarketScopeEvidence(
            source="web",
            url="https://example.com/post",
            snippet="We raised $5M for our legal AI tool.",
            as_of=self._now(),
        )
        dumped = e.model_dump(mode="json")
        assert dumped["source"] == "web"
        assert dumped["url"] == "https://example.com/post"
        assert dumped["snippet"] == "We raised $5M for our legal AI tool."
        assert dumped["company_id"] is None

    def test_invalid_source_rejected(self) -> None:
        """source is Literal['corpus', 'web'] — anything else is rejected."""
        with pytest.raises(ValidationError) as exc:
            MarketScopeEvidence(
                source="blog",  # type: ignore[arg-type]
                as_of=self._now(),
            )
        assert "source" in str(exc.value)

    def test_as_of_required(self) -> None:
        """as_of has no default — the timestamp is the audit trail."""
        with pytest.raises(ValidationError) as exc:
            MarketScopeEvidence(source="corpus", company_id=42)  # type: ignore[call-arg]
        assert "as_of" in str(exc.value)

    def test_extra_fields_forbidden(self) -> None:
        with pytest.raises(ValidationError):
            MarketScopeEvidence(  # type: ignore[call-arg]
                source="corpus",
                company_id=42,
                as_of=self._now(),
                extra_field="oops",
            )

    def test_datetime_serialises_as_iso8601(self) -> None:
        """Pydantic v2 serialises datetime as ISO-8601 on model_dump(mode='json').
        The frontend in api.ts types as_of as string — make sure the wire
        shape matches."""
        e = MarketScopeEvidence(source="corpus", company_id=42, as_of=self._now())
        js = e.model_dump(mode="json")
        assert isinstance(js["as_of"], str)
        assert js["as_of"].startswith("2026-07-02T")


# ---------------------------------------------------------------------------
# MarketScopeSignal — composition
# ---------------------------------------------------------------------------


class TestMarketScopeSignal:
    """The Phase 4 envelope carries direction + rationale + optional
    quantitative layer + confidence tier + ordered evidence list."""

    def _now(self) -> datetime:
        return datetime(2026, 7, 2, 9, 0, 0, tzinfo=timezone.utc)

    def test_minimal_signal_default_confidence(self) -> None:
        """Default confidence is 'directional' — matches the Phase 1.7 stub
        when the 4.2 deterministic rules don't fire."""
        s = MarketScopeSignal(
            direction=MarketScope.WIDE_OPEN,
            rationale="n=0 in local corpus, web fallback didn't fire either",
        )
        assert s.confidence == "directional"
        assert s.quantitative is None
        assert s.evidence == []

    def test_quantitative_signal_with_full_layer(self) -> None:
        q = MarketScopeQuant(
            competitor_count=120,
            recent_3y_count=20,
            saturation_index=0.6,
        )
        ev = MarketScopeEvidence(source="corpus", company_id=42, as_of=self._now())
        s = MarketScopeSignal(
            direction=MarketScope.SATURATED,
            rationale="competitor_count=120, growth_rate=0.17 → saturated",
            confidence="quantitative",
            quantitative=q,
            evidence=[ev],
        )
        dumped = s.model_dump(mode="json")
        assert dumped["direction"] == "saturated"
        assert dumped["confidence"] == "quantitative"
        assert dumped["quantitative"]["competitor_count"] == 120
        assert dumped["evidence"][0]["source"] == "corpus"

    def test_evidence_backed_with_web_entry(self) -> None:
        ev = MarketScopeEvidence(
            source="web",
            url="https://example.com/post",
            snippet="Niche legal AI for SMBs",
            as_of=self._now(),
        )
        s = MarketScopeSignal(
            direction=MarketScope.NICHE_BUT_REAL,
            rationale="n=3 corpus + web scrape finds a real but small wedge",
            confidence="evidence_backed",
            evidence=[ev],
        )
        dumped = s.model_dump(mode="json")
        assert dumped["confidence"] == "evidence_backed"
        assert dumped["quantitative"] is None
        assert len(dumped["evidence"]) == 1
        assert dumped["evidence"][0]["source"] == "web"

    def test_confidence_accepts_all_three_values(self) -> None:
        """The Literal type covers exactly the three tiers — exhaustive test."""
        for c in ("directional", "evidence_backed", "quantitative"):
            s = MarketScopeSignal(
                direction=MarketScope.WIDE_OPEN,
                rationale="r",
                confidence=c,  # type: ignore[arg-type]
            )
            assert s.confidence == c

    def test_invalid_confidence_rejected(self) -> None:
        with pytest.raises(ValidationError) as exc:
            MarketScopeSignal(
                direction=MarketScope.WIDE_OPEN,
                rationale="r",
                confidence="guessed",  # type: ignore[arg-type]
            )
        assert "confidence" in str(exc.value)

    def test_extra_fields_forbidden(self) -> None:
        with pytest.raises(ValidationError):
            MarketScopeSignal(  # type: ignore[call-arg]
                direction=MarketScope.WIDE_OPEN,
                rationale="r",
                bonus_field="oops",
            )

    def test_evidence_list_defaults_to_empty(self) -> None:
        s = MarketScopeSignal(direction=MarketScope.WIDE_OPEN, rationale="r")
        assert s.evidence == []


# ---------------------------------------------------------------------------
# IdeaVerdict — backwards-compat with Phase 1.7/1.8/1.11 fixtures
# ---------------------------------------------------------------------------


class TestIdeaVerdictBackwardsCompat:
    """The card body's hard rule: 'No breaking changes to the IdeaVerdict
    schema. The new fields are additive with sensible defaults.' These tests
    pin the contract that Phase 1.7 / 1.8 / 1.11 / 2.x / 3.x fixtures that
    don't set market_scope_signal still parse and serialize correctly."""

    def _minimal_competitor(self) -> CompetitorVerdict:
        return CompetitorVerdict(
            company_id=42,
            name="Dioptra",
            similarity_axes=["AI legal review"],
            key_differences=["vertical-only"],
            likely_failure_modes=["distribution"],
            evidence_links=[],
            confidence=0.7,
        )

    def test_legacy_shape_without_signal_parses(self) -> None:
        """Phase 1.7 fixture: market_scope_signal is null/absent."""
        v = IdeaVerdict(
            idea="AI legal contract review",
            top_competitors=[self._minimal_competitor()],
            market_scope=MarketScope.CROWDED_BUT_GROWING,
            market_scope_rationale="3 similar YC launches, none dominant",
            supporting_evidence=["https://yc.com/dioptra"],
        )
        assert v.market_scope == MarketScope.CROWDED_BUT_GROWING
        assert v.market_scope_signal is None
        assert v.market_scope_rationale == "3 similar YC launches, none dominant"

    def test_legacy_shape_dumps_without_signal_field(self) -> None:
        """The default=None envelope must NOT appear in JSON when null —
        the schema's default Pydantic behaviour, but worth pinning so a
        later refactor doesn't accidentally start serialising null."""
        v = IdeaVerdict(
            idea="AI legal contract review",
            top_competitors=[self._minimal_competitor()],
            market_scope=MarketScope.WIDE_OPEN,
            market_scope_rationale="stub",
        )
        dumped = v.model_dump(mode="json")
        # Pydantic v2 default: include nulls unless exclude_none=True.
        # We accept either shape — the wire contract is open. But the
        # MarketScope field is preserved as the 4-direction enum string.
        assert dumped["market_scope"] == "wide_open"
        assert dumped["market_scope_rationale"] == "stub"

    def test_market_scope_enum_strings_unchanged(self) -> None:
        """The four-direction enum values are the public API contract that
        the frontend's marketScope.ts colour-coded chip keys off. Adding
        a new field MUST NOT change these strings."""
        for scope in MarketScope:
            assert scope.value in {
                "wide_open",
                "crowded_but_growing",
                "saturated",
                "niche_but_real",
            }
        # Total count: exactly 4 (no additions).
        assert len(MarketScope) == 4

    def test_market_scope_signal_optional_with_none(self) -> None:
        """Explicit None is equivalent to default — Phase 1.7 callers
        that pre-set the field to None keep working."""
        v = IdeaVerdict(
            idea="AI legal contract review",
            top_competitors=[self._minimal_competitor()],
            market_scope=MarketScope.SATURATED,
            market_scope_rationale="stub",
            market_scope_signal=None,
        )
        assert v.market_scope_signal is None

    def test_market_scope_signal_populated_round_trips(self) -> None:
        """When populated by the 4.2/4.3/4.4 pipeline, the envelope
        direction mirrors the legacy market_scope field, and the
        confidence tier is one of the three allowed values."""
        q = MarketScopeQuant(
            competitor_count=120,
            recent_3y_count=20,
            saturation_index=0.6,
        )
        sig = MarketScopeSignal(
            direction=MarketScope.SATURATED,
            rationale="competitor_count=120, growth_rate=0.17",
            confidence="quantitative",
            quantitative=q,
        )
        v = IdeaVerdict(
            idea="AI legal contract review",
            top_competitors=[self._minimal_competitor()],
            market_scope=MarketScope.SATURATED,
            market_scope_rationale="competitor_count=120, growth_rate=0.17",
            market_scope_signal=sig,
        )
        dumped = v.model_dump(mode="json")
        assert dumped["market_scope"] == "saturated"
        assert dumped["market_scope_signal"]["direction"] == "saturated"
        assert dumped["market_scope_signal"]["confidence"] == "quantitative"
        assert dumped["market_scope_signal"]["quantitative"]["competitor_count"] == 120

    def test_market_scope_signal_direction_can_differ_from_market_scope(self) -> None:
        """The card body says the two fields CAN diverge — the legacy
        ``market_scope`` enum is the Phase 1.7 LLM call's output, and
        the 4.2/4.3/4.4 pipeline MAY override it. Pydantic doesn't
        enforce consistency between them; we keep that open by design."""
        sig = MarketScopeSignal(
            direction=MarketScope.SATURATED,
            rationale="4.2 rules say saturated",
            confidence="quantitative",
        )
        v = IdeaVerdict(
            idea="X",
            top_competitors=[],
            market_scope=MarketScope.WIDE_OPEN,  # legacy LLM stub still says wide_open
            market_scope_rationale="legacy",
            market_scope_signal=sig,
        )
        assert v.market_scope == MarketScope.WIDE_OPEN
        assert v.market_scope_signal is not None
        assert v.market_scope_signal.direction == MarketScope.SATURATED


# ---------------------------------------------------------------------------
# JSON Schema (OpenAPI) generation
# ---------------------------------------------------------------------------


class TestJsonSchemaGeneration:
    """The /ideas/analyze endpoint regenerates its OpenAPI schema from
    IdeaVerdict. The new field names must match the TypeScript wire types
    in src/frontend/src/lib/api.ts so the frontend can be rebuilt
    without a manual sync step."""

    def test_idea_verdict_schema_includes_market_scope_signal(self) -> None:
        schema = IdeaVerdict.model_json_schema()
        assert "market_scope_signal" in schema["properties"]

    def test_idea_verdict_schema_preserves_market_scope_enum(self) -> None:
        """The frontend reads verdict.market_scope as a MarketScope literal —
        the JSON schema must enumerate the same 4 strings."""
        schema = IdeaVerdict.model_json_schema()
        market_scope_schema = schema["properties"]["market_scope"]
        # Pydantic v2 emits enums under "$defs" for forward refs — but
        # top-level enum fields often inline. We accept either shape.
        # Just make sure all four strings appear somewhere in the schema.
        schema_text = json.dumps(schema)
        for v in ("wide_open", "crowded_but_growing", "saturated", "niche_but_real"):
            assert v in schema_text, f"missing enum value {v!r} in schema"

    def test_market_scope_quant_schema_matches_typescript(self) -> None:
        """The TypeScript MarketScopeQuant interface in
        src/frontend/src/lib/api.ts must mirror the JSON schema field names
        exactly — same keys, same casing, same nullability."""
        schema = MarketScopeQuant.model_json_schema()
        props = schema["properties"]
        assert set(props.keys()) == {
            "competitor_count",
            "recent_3y_count",
            "category_distribution",
            "search_volume_proxy",
            "saturation_index",
            "growth_rate",
        }
        # saturation_index is [0, 1].
        assert props["saturation_index"]["minimum"] == 0
        assert props["saturation_index"]["maximum"] == 1

    def test_market_scope_evidence_schema_includes_source_literal(self) -> None:
        schema = MarketScopeEvidence.model_json_schema()
        props = schema["properties"]
        assert "source" in props
        # source is a literal enum of {"corpus", "web"}; Pydantic v2
        # emits it under the anyOf-with-const shape OR a flat enum. Either
        # way, both strings must appear.
        schema_text = json.dumps(schema)
        assert "corpus" in schema_text
        assert "web" in schema_text

    def test_market_scope_signal_schema_includes_confidence_literal(self) -> None:
        schema = MarketScopeSignal.model_json_schema()
        props = schema["properties"]
        assert "confidence" in props
        schema_text = json.dumps(schema)
        for v in ("directional", "evidence_backed", "quantitative"):
            assert v in schema_text, f"missing confidence value {v!r}"


# ---------------------------------------------------------------------------
# Confidence — Literal type contract
# ---------------------------------------------------------------------------


class TestConfidenceLiteralContract:
    """MarketScopeConfidence is a typing.Literal — exhaustively pin the
    three allowed values so a future PR adding a fourth tier has to
    consciously update this test (and the docstring + frontend)."""

    def test_three_tiers_only(self) -> None:
        # Literal["directional", "evidence_backed", "quantitative"] —
        # Python's typing.get_args surfaces the three strings.
        import typing

        tiers = typing.get_args(MarketScopeConfidence)
        assert tiers == ("directional", "evidence_backed", "quantitative")

    def test_signal_rejects_unknown_confidence(self) -> None:
        """Even with all other fields valid, an unknown confidence value
        must fail validation — the Literal type guards the contract."""
        with pytest.raises(ValidationError):
            MarketScopeSignal(
                direction=MarketScope.WIDE_OPEN,
                rationale="r",
                confidence="ai_guessed",  # type: ignore[arg-type]
            )