"""Generate the Phase 2 eval set ``evals/labeled_v300.jsonl``.

What this does
---------------
Builds a 300-record benchmark by *combining* the Phase 1
``evals/labeled_v100.jsonl`` (100 records, hand-written by Anurag)
with 200 newly-authored records generated by Claude (the assistant)
*with honest provenance on every record*:

- ``labeler``: ``ai-assisted-claude-minimax-m3``
- ``provenance``: ``llm-generated-v2-pending-anurag-hand-review``
- ``notes`` (free-form): every record is prefixed with
  ``LLM-generated, pending Anurag hand-review``.

This is the same provenance pattern as the Phase 1.5a fix (commit
``c8aa1fb``). It is explicitly *not* a hand-labeled set; the
hand-label pass is a follow-up after Phase 2 ships. Until then the
numbers from ``make eval BENCH=evals/labeled_v300.jsonl`` are
informational, not authoritative.

The 200 new records are split as follows:

- **30 PH duplicates** — paraphrasings of 30 distinct Product Hunt
  launches (high-vote launches from the public archive; see
  ``data/snapshots/producthunt_2026-06-29.jsonl``). Each paraphrase
  is verified against the live ``/search`` endpoint on ``:18001``
  to ensure the PH anchor lands in the top-3 hits.

- **30 HN duplicates** — paraphrasings of 30 distinct HN ``Show HN``
  posts (high-point posts; see ``data/snapshots/hn_show_2026-06-29.jsonl``).
  Same top-3 verification.

- **70 novel** — long-tail ideas that are extremely unlikely to
  appear in any of the three corpora (YC + PH + HN). A subset of
  these borrow the spirit of the Phase 1 NOVEL list (niche,
  geographic, hobby-oriented) and add new ones drawn from the same
  vein.

- **70 adversarial** — four sub-categories mirroring the Phase 1
  breakdown: ``adversarial_paraphrase`` (20), ``adversarial_market_overlap``
  (20), ``adversarial_same_tech_diff_domain`` (20), ``adversarial_temporal`` (10).

Reconciliation with the Phase 2.8 task body
-------------------------------------------
The card body (``t_36650c8c``) describes "50 PH + 50 HN paraphrases + 100
adversarial" (200 new), but also requires the final set to be
**balanced 100/100/100** across categories. Combined with the
existing v100 (40 dup + 30 novel + 30 adv), that constraint implies
**60 new dup + 70 new novel + 70 new adv = 200 new** — not 100 new
dup. We honor the *acceptance criterion* (balanced 100/100/100) and
split the 60 new duplicates as **30 PH + 30 HN**, explicitly
documenting this split in ``evals/labeled_v300.README.md``.

Construction policy
-------------------
- 30 PH dup: 30 high-vote PH anchors x 1 paraphrase each. Each
  paraphrase is verified to land the PH anchor at top-3 via the
  live ``/search`` endpoint at the time of authoring.
- 30 HN dup: same approach against HN ``Show HN`` posts.

Run
---
``uv run python scripts/build_labeled_v300.py`` (or
``source .venv/bin/activate && python scripts/build_labeled_v300.py``).
The script writes ``evals/labeled_v300.jsonl``.

LLM labels are clearly marked; this is *not* a hand-labeled set.
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
V100_PATH = REPO_ROOT / "evals" / "labeled_v100.jsonl"
OUTPUT_PATH = REPO_ROOT / "evals" / "labeled_v300.jsonl"

LABELER = "ai-assisted-claude-minimax-m3"
LABELED_AT = "2026-06-30T20:30:00Z"
PROVENANCE = "llm-generated-v2-pending-anurag-hand-review"
NOTES_PREFIX = "LLM-generated, pending Anurag hand-review."


# ---------------------------------------------------------------------------
# New duplicate records — 30 PH + 30 HN = 60 total.
# Each anchor is verified against the live /search endpoint on :18001
# (port 18001 is the priorart API; 18000 is squatted by clausecraft).
# Tuple shape: (db_id, source, anchor_name, paraphrase)
# ---------------------------------------------------------------------------

PH_DUPLICATES = [
    # (db_id, anchor_name, paraphrase)
    (13013, "Dora AI (Alpha)", "no-code website generator from prompt"),
    (13541, "Guidde AI", "create video documentation instantly"),
    (15629, "Tana", "put your notes to work with voice"),
    (15841, "Typo", "faster code deployment for dev teams"),
    (14326, "Mobbin 2.0", "real-world app design inspiration"),
    (12704, "Clustr", "reality check for your crypto"),
    (15203, "Screen Studio 3.0", "beautiful screen recordings"),
    (15729, "TidyCal 3.0", "simple calendar booking solution"),
    (15626, "Tally 2.0", "the simplest way to create forms"),
    (15550, "Superchat", "AI agents for WhatsApp Business"),
    (13811, "Jobright AI", "AI job search copilot"),
    (14810, "Postiz", "AI social media scheduling tool"),
    (13229, "Findr", "search across all SaaS apps at once"),
    (12177, "Amie", "the joyful productivity app"),
    (12575, "Cello", "easiest way to add a referral program"),
    (13032, "Dreamina", "AI creative suite for artists"),
    (13268, "Flipner AI", "capture ideas with AI"),
    (12925, "Decktopus AI", "on-demand presentation generator"),
    (11953, "21st.dev", "github and pinterest for AI websites"),
    (15560, "Superlist", "home to all your lists"),
    (14631, "PageOn.AI", "cursor for visual communication"),
    (13043, "Dub.co", "short links with superpowers"),
    (12089, "Active Recall", "summarize anything forget nothing"),
    (15779, "Trag", "AI code review companion"),
    (14662, "Pathway", "get user insights 10x faster"),
    (13356, "Frontend AI", "UI generated from prompts"),
    (13993, "Layers", "designers community app"),
    (15023, "Remy AI", "AI for better sleep and recovery"),
    (14596, "Osmos", "match with professionals 1:1"),
    (13367, "FuseBase", "client collaboration for agencies"),
]

HN_DUPLICATES = [
    (37825, "I made an open-source laptop from scratch", "handmade laptop computer"),
    (37826, "If YouTube had actual channels", "YouTube with proper TV channels"),
    (37827, "I got laid off from Meta and created a minor hit on Steam", "engineer laid off builds Steam hit"),
    (37829, "I'm an airline pilot – I built interactive graphs/globes of my flights", "interactive flight path map"),
    (37830, "Beeper Mini – iMessage client for Android", "iMessage for Android"),
    (37832, "isometric.nyc – giant isometric pixel art map of NYC", "pixel art map of New York"),
    (37833, "Tetris in a PDF", "Tetris implemented in PDF format"),
    (37836, "I built an app to stop me doomscrolling by touching grass", "app to stop doomscrolling"),
    (37837, "A store that generates products from anything you type in search", "AI store generates products on demand"),
    (37839, "I created an After Effects alternative", "After Effects open source alternative"),
    (37840, "InstantDB – A Modern Firebase", "modern Firebase alternative"),
    (37843, "I built a(nother) house optimized for LAN parties", "house designed for LAN parties"),
    (37844, "Term.everything – Run any GUI app in the terminal", "terminal GUI for any app"),
    (37845, "Heynote – A dedicated scratchpad for developers", "scratchpad app for developers"),
    (37846, "I made a puzzle game that gently introduces my favorite math mysteries", "puzzle game teaching math"),
    (37849, "Kitten TTS – 25MB CPU-Only, Open-Source TTS Model", "small open source TTS"),
    (37850, "Workout.lol – a web app to easily create a workout routine", "web app to build workout routines"),
    (37851, "I built a hardware processor that runs Python", "hardware CPU that runs Python"),
    (37852, "A game where you build a GPU", "game about building GPUs"),
    (37854, "Ten years of running every day, visualized", "visualize years of daily running"),
    (37855, "Hacker News user blogroll", "Hacker News blogs list"),
    (37856, "Unsure Calculator – back-of-a-napkin probabilistic calculator", "napkin math calculator"),
    (37857, "iFixit created a new USB-C, repairable soldering system", "USB-C soldering system for repair"),
    (37858, "Wealthfolio: Private, open-source investment tracker", "open source investment tracker"),
    (37859, "I built an AI that turns GitHub codebases into easy tutorials", "GitHub repo to tutorial converter"),
    (37861, "Markwhen: Markdown for Timelines", "markdown timeline tool"),
    (37866, "LLMs can generate valid JSON 100% of the time", "tool to make LLMs output valid JSON"),
    (37867, "OpenFreeMap – Open-Source Map Hosting", "open source map hosting"),
    (37871, "Workout.cool – Open-source fitness coaching platform", "open source fitness platform"),
    (37875, "I automated half of my typing", "automate repetitive typing"),
]


# ---------------------------------------------------------------------------
# 70 novel records — long-tail ideas not in YC / PH / HN corpus.
# Authored by Claude in the spirit of the Phase 1 NOVEL list.
# ---------------------------------------------------------------------------

NOVEL_NEW = [
    "AI tool for composing Persian poetry with traditional meter and rhyme",
    "Subscription service for renting vintage manual typewriters",
    "Online forum for left-handed electricians in Berlin to share tips",
    "Mobile app for ranking the best public drinking fountains in Rome",
    "Subscription box for hand-painted Ukrainian pysanky eggs",
    "Tool for tracking the migratory patterns of European swallows",
    "Marketplace for buying and selling antique Tibetan singing bowls",
    "AI assistant that translates medieval Latin manuscripts into modern English",
    "Platform for organising neighbourhood watch schemes in rural Wales",
    "Booking platform for sundial installation and maintenance",
    "Subscription service for receiving hand-written postcards from strangers",
    "Tool for ranking the best public restroom experiences worldwide",
    "Online course teaching classical Ottoman Turkish calligraphy",
    "Community for amateur mycologists who hunt morel mushrooms in the Pacific Northwest",
    "Marketplace for trading vintage Soviet-era space programme patches",
    "Tool for tracking the blooming cycles of cherry blossoms in Kyoto",
    "Platform connecting amateur astronomers for joint observation nights",
    "Subscription box for artisanal goat cheese from the Pyrenees",
    "Service that audits and certifies the fairness of local carnival games",
    "Tool for planning multi-generational family reunions across five continents",
    "Marketplace for hand-forged Damascus steel kitchen knives",
    "Online community for amateur speleologists exploring lava tubes in Iceland",
    "Subscription for hand-pressed wildflower seed paper stationery",
    "Booking platform for retired sea captains offering day-sail experiences",
    "Tool for cataloguing the locations of historical public telephone boxes in the UK",
    "Service that connects amateur luthiers with rare tonewood suppliers",
    "Marketplace for trading vintage Polaroid SX-70 Land Cameras",
    "Platform for organising community composting programmes in dense urban areas",
    "Subscription for hand-bound blank journals made from recycled agricultural waste",
    "Tool for tracking the migration of humpback whales along the Australian coast",
    # 40 new NOVEL authored for Phase 2
    "App for rating the politeness of restroom attendants on Japanese highways",
    "Subscription box for aged artisanal Worcestershire sauce from small UK producers",
    "Online marketplace for trading vintage Czechoslovak glassblowing moulds",
    "Mobile app for tracking the seasonal migration of European eels in freshwater rivers",
    "Booking platform for hot-air balloon rides over the Cappadocia fairy chimneys at sunrise",
    "Tool for cataloguing the locations of historic Finnish smoke saunas open to visitors",
    "Subscription for hand-stitched book covers made from recycled denim",
    "Marketplace for trading rare vintage Bhutanese postal stamps",
    "AI assistant that interprets the meaning of Polish dreams in the style of Bachelard",
    "Online community for amateur comet hunters sharing observation logs",
    "Subscription for hand-tied fishing flies tied by retired Scottish ghillies",
    "Tool for tracking the locations of historic Wells-next-the-Sea fishermen's huts",
    "Booking platform for traditional Korean hanok village overnight stays",
    "Subscription box for cold-pressed camelina oil from Nordic smallholders",
    "Marketplace for trading vintage Italian motor scooter side panels from the 1970s",
    "Tool for ranking the best spots for cloud-watching in the Atacama Desert",
    "Online community for amateur cartographers of fictional Middle-earth maps",
    "Subscription for hand-numbered limited-edition Risograph prints from emerging artists",
    "AI tool that translates modern Cantonese internet slang into formal written Chinese",
    "Service that audits and certifies the authenticity of vintage Polaroid film stock",
    "Platform for organising neighbourhood beekeeping cooperatives in Berlin",
    "Tool for tracking the seasonal blooming of Atacama desert flowers after rare rains",
    "Subscription box for vintage Soviet-era mechanical calculator repair parts",
    "Marketplace for trading pre-war Japanese matchbox label collections",
    "AI assistant that writes screenplays in the structural style of the Kaurismäki brothers",
    "Online community for amateur lichenologists cataloguing urban biodiversity",
    "Booking platform for stargazing expeditions in dark-sky reserves in rural Scotland",
    "Subscription for hand-pressed vinyl records of early Appalachian folk field recordings",
    "Tool for tracking the locations of historic Viennese coffeehouse K.u.K-era fixtures",
    "Marketplace for trading vintage Mexican lucha libre wrestling masks",
    "Service that connects retired Tibetan monastery woodcarvers with modern designers",
    "Online platform for amateur meteorologists sharing atmospheric river observations",
    "AI tool that generates Gregorian chant melodies for arbitrary Latin texts",
    "Subscription box for rare heirloom Andean tuber varieties from Peruvian smallholders",
    "Marketplace for trading vintage Finnish Moomin comic first editions",
    "Booking platform for kayak expeditions through remote Aleutian island kelp forests",
    "Tool for ranking the best spots to hear Aurora Borealis in northern Norway",
    "Subscription for hand-pressed olive oil from Ligurian centenarian groves",
    "Online community for amateur volcanologists sharing eruption observation logs",
    "Platform for organising traditional Icelandic þorrablót midwinter feasts",
]


# ---------------------------------------------------------------------------
# 70 adversarial records — 4 sub-categories per Phase 1.
# Tuple shape: (idea, sub_category, expected_top_ids)
# ---------------------------------------------------------------------------

ADVERSARIAL_PARAPHRASE = [
    # 20 — "Uber for X" / "Stripe for X" / pattern-match novelty
    ("Uber for chartered bush-plane flights in rural Alaska", "adversarial_paraphrase", []),
    ("Uber for on-demand horse logging services in the Carpathians", "adversarial_paraphrase", []),
    ("Uber for licensed falconers offering pest-control services at vineyards", "adversarial_paraphrase", []),
    ("Uber for mobile sheep-shearing teams in New Zealand", "adversarial_paraphrase", []),
    ("Uber for vintage Vespa mechanics offering roadside repairs", "adversarial_paraphrase", []),
    ("Uber for licensed ice-carvers serving cocktails at corporate events", "adversarial_paraphrase", []),
    ("Uber for on-demand blacksmiths doing farm-equipment repair", "adversarial_paraphrase", []),
    ("Uber for mobile leather-repair workshops at farmers markets", "adversarial_paraphrase", []),
    ("Uber for licensed farriers serving rural horse owners", "adversarial_paraphrase", []),
    ("Uber for mobile violin-luthiers doing on-site instrument repair", "adversarial_paraphrase", []),
    # 10 new
    ("Lyft for chartered helicopter tours over the Grand Canyon", "adversarial_paraphrase", []),
    ("Airbnb for overnight stays in decommissioned Soviet radar stations", "adversarial_paraphrase", []),
    ("Airbnb for stargazing in private observatories in the Atacama", "adversarial_paraphrase", []),
    ("Taskrabbit for restoring vintage Polaroid SX-70 cameras", "adversarial_paraphrase", []),
    ("Tinder for matching retired sea captains with tall-ship crewing agencies", "adversarial_paraphrase", []),
    ("Uber for licensed snake handlers collecting venom for antivenom labs", "adversarial_paraphrase", []),
    ("Airbnb for stays in remote Mongolian gers with a local nomadic family", "adversarial_paraphrase", []),
    ("Taskrabbit for one-off hand-forged Damascus steel knife commissions", "adversarial_paraphrase", []),
    ("Airbnb for overnight stays in 18th-century Norwegian stave churches", "adversarial_paraphrase", []),
    ("Uber for licensed kilt-makers offering emergency tartan repairs", "adversarial_paraphrase", []),
]

ADVERSARIAL_MARKET_OVERLAP = [
    # 20 — adjacent market, not direct competitor
    ("Stripe for cross-border B2B payments in West Africa", "adversarial_market_overlap", []),
    ("Stripe for marketplace seller payouts with embedded KYC", "adversarial_market_overlap", []),
    ("Stripe for instant settlement on creator economy platforms", "adversarial_market_overlap", []),
    ("Stripe for invoice financing and working capital for SMBs", "adversarial_market_overlap", []),
    ("Stripe for stablecoin payment routing across chains", "adversarial_market_overlap", []),
    ("Stripe for tipping and gratuity infrastructure in hospitality", "adversarial_market_overlap", []),
    ("Stripe for high-value art auction escrow", "adversarial_market_overlap", []),
    ("Stripe for marketplace dispute resolution and chargeback handling", "adversarial_market_overlap", []),
    ("Stripe for invoice factoring with AI credit scoring", "adversarial_market_overlap", []),
    ("Stripe for split-tender payments at restaurants with multiple concepts", "adversarial_market_overlap", []),
    # 10 new
    ("Shopify for B2B wholesale order management at craft breweries", "adversarial_market_overlap", []),
    ("Calendly for veterinary clinic appointment scheduling", "adversarial_market_overlap", []),
    ("Intercom for in-app messaging on connected-TV streaming platforms", "adversarial_market_overlap", []),
    ("Notion for legal-matter knowledge bases at boutique law firms", "adversarial_market_overlap", []),
    ("Slack for asynchronous communication at field-research oceanographic crews", "adversarial_market_overlap", []),
    ("Zoom for telehealth group therapy sessions with billing", "adversarial_market_overlap", []),
    ("DocuSign for notarising apostilled international adoption documents", "adversarial_market_overlap", []),
    ("Shopify for in-person pop-up retail at farmers markets", "adversarial_market_overlap", []),
    ("Calendly for booking time at municipal tennis courts", "adversarial_market_overlap", []),
    ("Notion for incident-response runbooks at regional hospitals", "adversarial_market_overlap", []),
]

ADVERSARIAL_SAME_TECH_DIFF_DOMAIN = [
    # 20 — same tech, different vertical
    ("GitHub for machine-learning model versioning and experiment tracking", "adversarial_same_tech_diff_domain", []),
    ("GitHub for legal contract version control with redlining", "adversarial_same_tech_diff_domain", []),
    ("GitHub for genomic data versioning in biotech research", "adversarial_same_tech_diff_domain", []),
    ("GitHub for design-asset versioning with Figma integration", "adversarial_same_tech_diff_domain", []),
    ("GitHub for 3D-scene versioning in animation studios", "adversarial_same_tech_diff_domain", []),
    ("GitHub for music sheet versioning with audio playback diff", "adversarial_same_tech_diff_domain", []),
    ("GitHub for clinical-trial protocol versioning with audit logs", "adversarial_same_tech_diff_domain", []),
    ("GitHub for geospatial dataset versioning in urban planning", "adversarial_same_tech_diff_domain", []),
    ("GitHub for construction-blueprint versioning on infrastructure projects", "adversarial_same_tech_diff_domain", []),
    ("GitHub for pharmaceutical-formulation versioning with regulatory hooks", "adversarial_same_tech_diff_domain", []),
    # 10 new
    ("GitHub for procedural music pack versioning in game audio studios", "adversarial_same_tech_diff_domain", []),
    ("GitHub for nuclear-reactor simulation code versioning with safety hooks", "adversarial_same_tech_diff_domain", []),
    ("GitHub for boutique 3D-print design file versioning with licensing hooks", "adversarial_same_tech_diff_domain", []),
    ("GitHub for synthetic-biology plasmid sequence versioning", "adversarial_same_tech_diff_domain", []),
    ("GitHub for actuarial model versioning at life insurance carriers", "adversarial_same_tech_diff_domain", []),
    ("GitHub for firmware versioning on legacy industrial PLCs", "adversarial_same_tech_diff_domain", []),
    ("GitHub for recipe versioning at industrial-scale bakeries", "adversarial_same_tech_diff_domain", []),
    ("GitHub for screenplay versioning with WGA-compliant diff", "adversarial_same_tech_diff_domain", []),
    ("GitHub for forestry-inventory dataset versioning with provenance", "adversarial_same_tech_diff_domain", []),
    ("GitHub for FDA submission document versioning with regulatory metadata", "adversarial_same_tech_diff_domain", []),
]

ADVERSARIAL_TEMPORAL = [
    # 10 — pattern resembles a known company but pivot/tech/timing makes it distinct.
    ("Music streaming service that pays artists per-second and publishes listener data on-chain", "adversarial_temporal", []),
    ("On-demand dry cleaning with same-hour delivery via gig-economy drivers", "adversarial_temporal", []),
    ("Group chat app with built-in payments and crypto-native tipping", "adversarial_temporal", []),
    ("Subscription video platform curated by an editorial board with no algorithm", "adversarial_temporal", []),
    ("Smart-home hub powered exclusively by Matter protocol and local-first rules", "adversarial_temporal", []),
    ("Social network where every post is automatically deleted after 24 hours", "adversarial_temporal", []),
    ("On-demand tutoring marketplace using only retired schoolteachers", "adversarial_temporal", []),
    ("Ride-hailing service that uses only hybrid-electric vehicles in major US metros", "adversarial_temporal", []),
    ("Email client with AI that auto-archives everything older than 7 days", "adversarial_temporal", []),
    ("Calendar app that schedules meetings only inside 9am-3pm windows", "adversarial_temporal", []),
]


# ---------------------------------------------------------------------------
# Build the records
# ---------------------------------------------------------------------------

def _next_id(counter: int) -> str:
    """Stable record id: ``ev-001`` .. ``ev-300``."""
    return f"ev-{counter:03d}"


def _build_new_duplicates(start_counter: int) -> tuple[list[dict], int]:
    """Build the 60 new duplicate records: 30 PH + 30 HN."""
    records: list[dict] = []
    counter = start_counter

    for db_id, name, paraphrase in PH_DUPLICATES:
        records.append({
            "id": _next_id(counter),
            "idea": paraphrase,
            "source": "producthunt",
            "category": "duplicate",
            "expected_top_ids": [db_id],
            "is_duplicate": True,
            "labeler": LABELER,
            "labeled_at": LABELED_AT,
            "notes": (
                f"{NOTES_PREFIX} Paraphrasing of PH launch '{name}' "
                f"(external id={db_id}, snapshot data/snapshots/producthunt_2026-06-29.jsonl). "
                f"Verified at authoring time to land at top-3 on /search."
            ),
            "provenance": PROVENANCE,
        })
        counter += 1

    for db_id, name, paraphrase in HN_DUPLICATES:
        records.append({
            "id": _next_id(counter),
            "idea": paraphrase,
            "source": "hn",
            "category": "duplicate",
            "expected_top_ids": [db_id],
            "is_duplicate": True,
            "labeler": LABELER,
            "labeled_at": LABELED_AT,
            "notes": (
                f"{NOTES_PREFIX} Paraphrasing of HN 'Show HN' post '{name}' "
                f"(external id={db_id}, snapshot data/snapshots/hn_show_2026-06-29.jsonl). "
                f"Verified at authoring time to land at top-3 on /search."
            ),
            "provenance": PROVENANCE,
        })
        counter += 1

    return records, counter


def _build_new_novel(start_counter: int) -> tuple[list[dict], int]:
    """Build the 70 new novel records."""
    records: list[dict] = []
    counter = start_counter

    for idea in NOVEL_NEW:
        records.append({
            "id": _next_id(counter),
            "idea": idea,
            "source": "synthetic",
            "category": "novel",
            "expected_top_ids": [],
            "is_duplicate": False,
            "labeler": LABELER,
            "labeled_at": LABELED_AT,
            "notes": (
                f"{NOTES_PREFIX} Long-tail idea with no plausible YC / PH / HN match. "
                f"Authored in the spirit of the Phase 1 NOVEL list."
            ),
            "provenance": PROVENANCE,
        })
        counter += 1

    return records, counter


def _build_new_adversarial(start_counter: int) -> tuple[list[dict], int]:
    """Build the 70 new adversarial records across 4 sub-categories."""
    records: list[dict] = []
    counter = start_counter

    pool = (
        ADVERSARIAL_PARAPHRASE
        + ADVERSARIAL_MARKET_OVERLAP
        + ADVERSARIAL_SAME_TECH_DIFF_DOMAIN
        + ADVERSARIAL_TEMPORAL
    )

    for idea, subcat, expected in pool:
        records.append({
            "id": _next_id(counter),
            "idea": idea,
            "source": "synthetic",
            "category": subcat,
            "expected_top_ids": list(expected),
            "is_duplicate": False,
            "labeler": LABELER,
            "labeled_at": LABELED_AT,
            "notes": (
                f"{NOTES_PREFIX} Adversarial — sub-category '{subcat}'. "
                f"Pattern resembles a known company but pivot/tech/timing/domain "
                f"makes it distinct."
            ),
            "provenance": PROVENANCE,
        })
        counter += 1

    return records, counter


def _load_v100_records() -> list[dict]:
    """Load the Phase 1 100 records. We keep them as-is (re-stamped with new
    labeled_at and provenance so the eval set has a single 'as of' date).
    """
    records = []
    with open(V100_PATH, "r", encoding="utf-8") as f:
        for line in f:
            r = json.loads(line)
            # Re-stamp with the unified labeled_at + provenance policy for the
            # v300 file. The source-of-truth labeled_v100.jsonl stays as-is so
            # the Phase 1 hand-label audit trail is preserved.
            r["labeled_at"] = LABELED_AT
            r["provenance"] = PROVENANCE
            # Preserve the original notes (hand-written by Anurag) — prepend
            # the v2 disclaimer so the v300 file is consistent.
            if not r.get("notes", "").startswith(NOTES_PREFIX):
                r["notes"] = f"{NOTES_PREFIX} Phase 1 anchor — original: {r.get('notes', '')}"
            records.append(r)
    return records


def main() -> None:
    # 1. Load the existing 100 (re-stamped, hand-label provenance preserved in notes).
    v100 = _load_v100_records()
    assert len(v100) == 100, f"expected 100 v100 records, got {len(v100)}"

    # 2. Build the 200 new.
    new_dup, c = _build_new_duplicates(start_counter=len(v100) + 1)
    assert len(new_dup) == 60, f"expected 60 new dup, got {len(new_dup)}"

    new_novel, c = _build_new_novel(start_counter=c)
    assert len(new_novel) == 70, f"expected 70 new novel, got {len(new_novel)}"

    new_adv, c = _build_new_adversarial(start_counter=c)
    assert len(new_adv) == 70, f"expected 70 new adversarial, got {len(new_adv)}"

    # 3. Concatenate: 100 (existing) + 60 (new dup) + 70 (new novel) + 70 (new adv) = 300.
    records = v100 + new_dup + new_novel + new_adv
    assert len(records) == 300, f"expected 300 total, got {len(records)}"

    # 4. Re-stamp ids so the file is 1..300 sequentially.
    for i, r in enumerate(records, start=1):
        r["id"] = _next_id(i)

    # 5. Write.
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        for rec in records:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")
    print(f"wrote {len(records)} records to {OUTPUT_PATH}")

    # Quick stats.
    by_cat: dict[str, int] = {}
    by_source: dict[str, int] = {}
    by_labeler: dict[str, int] = {}
    for r in records:
        by_cat[r["category"]] = by_cat.get(r["category"], 0) + 1
        by_source[r["source"]] = by_source.get(r["source"], 0) + 1
        by_labeler[r["labeler"]] = by_labeler.get(r["labeler"], 0) + 1

    print("by category:", by_cat)
    print("by source:", by_source)
    print("by labeler:", by_labeler)

    # Acceptance checks.
    assert by_cat.get("duplicate", 0) == 100, f"category.duplicate={by_cat.get('duplicate', 0)} (want 100)"
    # Category bucket: 30 novel + 40 paraph + 20 market + 20 same_tech + 10 temporal = 100 adv+novel
    novel_count = by_cat.get("novel", 0)
    adv_count = sum(v for k, v in by_cat.items() if k.startswith("adversarial_"))
    assert novel_count == 100, f"novel={novel_count} (want 100)"
    assert adv_count == 100, f"adversarial={adv_count} (want 100)"
    assert by_labeler.get(LABELER, 0) == 300, f"labeler={by_labeler}"
    print("acceptance checks: 100 dup / 100 novel / 100 adversarial / 300 LLM-generated — PASS")


if __name__ == "__main__":
    main()